### ISSUE TITLE
skeleton-template dependency

### ISSUE THREAD

**Issue by christopheg** [tigron/skeleton-core#1]
There seems to be a dependency which is not required in composer.json.
The idea of Skeleton was to have several stand-alone packages. If we want to follow this, I think it would be better to make this dependency optional.
I see at least 2 problems in lib/Skeleton/Core/Web/Module.php:

line 48:
`		// Find the template and set it up
		$template = \Skeleton\Core\Web\Template::Get();
		$template->add_environment('module', $this);
		$template->add_environment('sticky_session', $sticky->get_as_array());`

line 102:
`		$template = \Skeleton\Core\Web\Template::Get();`

I think we should check if the template class is available. If not, these actions are not required

**Comment by gerryd** [comment]
Fixed with 0bfe7b0c83ac1a807df919115b36c1d3f829b28e
